### ISSUE TITLE
git-branch-repo

### ISSUE THREAD

**Issue by GPopZach** [bokub/git-history-editor#13]
Hey! Not a _huge_ issue or anything, but it might be worth looking into replacing `filter-branch` with `filter-repo`. It's now the officially accepted tool for this, and solves a lot of the headaches `filter-branch` brings up. Should be a pretty trivial conversion, I'm willing to do it and just submit a PR if it's not something you're interested in doing yourself -- as long as I wouldn't be wasting my time with a PR that'll sit there for a few years lmao.

**Comment by bokub** [comment]
Hi ! Sorry for the wait

Will `git filter-repo` work with the same arguments as `git filter-branch`? Or would you change the arguments too ?

**Comment by bokub** [comment]
I'm afraid that most people don't have the last git version installed (that's my case), and will have an error message when trying to run `git filter-repo`

**Comment by GPopZach** [comment]
The syntax is different, but the changes are relatively straightforward. Like I said it’s biggest plus is that it addresses a lot of the conceptual issues with `git-filter-branch`. As far as I know it should be compatible with any version of git that’s even remotely recent, but I could be wrong, I can look into it for you, and if you’re wanting to go that route we can collaborate on an implementation if you’d like the help. How far back of a version are we talking?

**Comment by bokub** [comment]
From what I understand, `filter-repo` is recommended by git but it not part of the `git` command line, it's just an external tool.

This project is supposed to be straightforward, just a no-brain copy/paste. I don't want to ask the users "please install another external tool so command project can work for you", that would make this project useless
