### ISSUE TITLE
Editing hour, minute and second values increase by two instead of one

### ISSUE THREAD

**Issue by PoLaKoSz** [bokub/git-history-editor#15]
When I click the up or down arrow in the time editing popup the value increase or decrease by two instead of one.

Tested with:
- Brave [Version 1.24.86](https://github.com/brave/brave-browser/releases/tag/v1.24.86) Chromium: 90.0.4430.212 (clean guest window)
- Firefox [88.0.1](https://www.mozilla.org/en-US/firefox/88.0.1/releasenotes/) (private window)

_I wanted to debug the issue but I'm not familiar with Vue.js and wasn't able to render the index.html properly to even start._

**Comment by bokub** [comment]
I've tested with Firefox 88.0.1 (64-bit) and Chrome 90.0.4430.212 (64-bit) and couldn't reproduce your issue...

Can you send a video?

Are there warnings or errors in the JavaScript console? (F12)

**Comment by PoLaKoSz** [comment]
Thanks for the fast response!

Here is the video:

https://user-images.githubusercontent.com/1327533/119496424-c46fb800-bd63-11eb-8d46-630341cba0a4.mp4

**Comment by bokub** [comment]
That's so strange... :confused: I tried with brave and I still cannot reproduce the problem...

- Can you include the data you pasted? (or does it happen with any data?)
- ~What is your OS?~ Looks like it's windows
- Does it happen only in private browsing ? or all the time?
- Are you 100% sure it's not one of your extensions ?

**Comment by PoLaKoSz** [comment]
I'm gonna close this issue, because this is probably on my end.

- This issue happens with all of my commit history, but here is one:
```
$ git log -3 --pretty=format:"%H*#%an*#%ae*#%at*#%s" | base64 | tr -d "\n"
ZjIyNjcxZjUxMWZiOWMwM2NlYzRlZTQ4NWMyZmM3Mzc0MjUwNDcyYiojQm9yaXMgS3ViaWFrKiNrdWJpYWtib3Jpc0BnbWFpbC5jb20qIzE1OTM3ODQxNDMqI0ZpeCB0eXBvCjhiYjg5NGZiYjBjY2M3OGMyNThjNDNmOTE4NDkwZmU3ZTBmZmNmZmUqI0JvcmlzIEt1Ymlhayoja3ViaWFrYm9yaXNAZ21haWwuY29tKiMxNTkzNzgzODU1KiNSZW1vdmUgaW1wb3J0IHNjcmlwdC4gRml4ZXMgICMxMQozZTY4MmU5ODFhNzFlOGQ4OThhOGQ3ZTgwNGFhZTE0M2E5MDE1ZGRhKiNCb3JpcyBLdWJpYWsqI2t1Ymlha2JvcmlzQGdtYWlsLmNvbSojMTU5Mzc3ODg3OSojVXNlIGpzRGVsaXZyIENETiB3aXRoIGNvbWJpbmUgZmVhdHVyZQ==
```
- Its a Windows 10 Pro 20H2 19042.985
- It happens with any kind of browser (just tested on Chrome Version 90.0.4430.212 (Official Build) (64-bit)), no matter if private window or not, with or without any extension so I'm 99.99% sure its not an extension sideeffect.


### Update ​2021. 06. 07.

In Brave Version 1.25.70 Chromium: 91.0.4472.77 (Official Build) (64-bit) this problem is ~gone~ still exists.
