### ISSUE TITLE
Missed build files

### ISSUE THREAD

**Issue by decodedbrain** [bokub/git-history-editor#5]
Please add build-script or compiled version of stylesheet.sass and index.html.
Version from repo does't work properly out-of-the-box

**Comment by bokub** [comment]
Yeah, it was never designed to work outside of [git.io/editor.](http://git.io/editor)
Maybe I could make a release of it. 

Why do you need it? Offline usage, or contribution? 

By the way, the build is made by Gihub pages, so you just have to run `Jekyll `to compile it.

**Comment by bokub** [comment]
I'm closing the issue.

Short answer: [install jekyll](https://jekyllrb.com/docs/installation/), then run `jekyll build` or `jekyll serve`
