### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by PoLaKoSz** [bokub/git-history-editor#8]
Hi!

Thank You for this great tool!

By default `git filter-branch` loops through the hole repository history so even with a few hundred commits can slow the history editing dramatically.

## How to speed up the generated script execution
`git filter-branch` [support partial history rewriting ](https://git-scm.com/docs/git-filter-branch#_examples)

> To restrict rewriting to only part of the history, specify a revision range in addition to the new branch name. The new branch name will point to the top-most revision that a git rev-list of this range will print.
> 
> Consider this history:
> 
> ```
>      D--E--F--G--H
>     /     /
> A--B-----C
> ```
> 
> To rewrite only commits D,E,F,G,H, but leave A, B and C alone, use:
> 
> ```
> git filter-branch ... C..H
> ```

For example this is the generated script:
```
git filter-branch --env-filter \
'if test "$GIT_COMMIT" = "5f24fbf8ecdfe3a200c8a0feb8e8bc9687d8972e"; then
    export GIT_AUTHOR_DATE="1578751363"
    export GIT_COMMITTER_DATE="1578751363"
fi' && rm -fr "$(git rev-parse --git-dir)/refs/original/"
```

Improved solution:
```diff
  git filter-branch --env-filter \
  'if test "$GIT_COMMIT" = "5f24fbf8ecdfe3a200c8a0feb8e8bc9687d8972e"; then
     export GIT_AUTHOR_DATE="1578751363"
     export GIT_COMMITTER_DATE="1578751363"
- fi' && rm -fr "$(git rev-parse --git-dir)/refs/original/"
+ fi' 3c48843..HEAD && rm -fr "$(git rev-parse --git-dir)/refs/original/"
```

**3c48843** is the oldest edited commit's parent hash.

## Other benefits
Running the generated script (without the improvement) can cause for some repositories to 'clone' the whole branch commits with a different hash but with the proposed solution this behaviour can be prevented.

#### Steps to reproduce
_In progress_

**Comment by bokub** [comment]
I found some free time

It's fixed ! 🎉

**Comment by PoLaKoSz** [comment]
Thank You! :smile:
