### ISSUE TITLE
use commit range to avoid rewriting too much

### ISSUE THREAD

**Issue by avilleret** [bokub/git-history-editor#9]
I modified the date of the last 3 commits on my repo which have not been pushed yet.
Doing so end up rewriting the history of the last 212 commits. Those are 209 already pushed commits.

To avoid that, I add a commit range at the end of the command line : 

```
git filter-branch --env-filter \
'if test "$GIT_COMMIT" = "c3bd0b5878f4f06c3f8482033750f83724ffc214"; then
    export GIT_AUTHOR_DATE="1593646151"
    export GIT_COMMITTER_DATE="1593646151"
elif test "$GIT_COMMIT" = "df3d1a15076dc8f8b1da1c87a0d005f80178ddd8"; then
    export GIT_AUTHOR_DATE="1593646121"
    export GIT_COMMITTER_DATE="1593646121"
elif test "$GIT_COMMIT" = "2629a79db5e33088c8cac021973fbad558b12977"; then
    export GIT_AUTHOR_DATE="1593642562"
    export GIT_COMMITTER_DATE="1593642562"
fi' 2629a79db5e33088c8cac021973fbad558b12977^..HEAD && rm -fr "$(git rev-parse --git-dir)/refs/original/"
```

note the extra `2629a79db5e33088c8cac021973fbad558b12977^..HEAD` 
I'm using the `^` suffix to point to the parent commit of `2629a79` which is the farest commit I want to modify.

**Comment by bokub** [comment]
That would be a great improvement, yeah

I may work on it if I have some free time soon

**Comment by bokub** [comment]
I found some free time

Now fixed ! 🎉

**Comment by avilleret** [comment]
awesome ! I was preparing kind of the same !

thanks a lot !
